kegg_dir: /vortexfs1/omics/alexander/data/KEGG/
kegg_db: /vortexfs1/omics/alexander/data/KEGG/genes/fasta/family_eukaryotes.pep
pfam_dir: /vortexfs1/omics/alexander/halexander/MAGpy-setup/
mag_dir: ../euk-mags 
temp_dir: /vortexfs1/scratch/halexander/metaeuk/tempdir
metaeuk_db: /vortexfs1/scratch/halexander/metaeuk/MMETSP_uniclust50_MERC
busco_group: eukaryota_odb10
